spring:
  application:
    name: Roadmaps
  datasource:
    url: jdbc:postgresql://${PGSQL_SERVICE_HOST}:${PGSQL_SERVICE_PORT}/${PGSQL_SERVICE_DB}
    username: ${PGSQL_SERVICE_USERNAME}
    password: ${PGSQL_SERVICE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloud:
  aws:
    s3:
      endpoint: ${R2_ENDPOINT}
      region: us-east-1
      bucket: ${R2_BUCKET_NAME}
    credentials:
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}
      public-url: ${R2_PUBLIC_URL}

jwt:
  secret:${JWT_SECRET}
  accessTokenExpiration:${JWT_ACCESS_TOKEN_EXPIRATION}


frontendBaseUrl: ${FRONTEND_BASE_URL}